### ISSUE TITLE
Deployment problems

### ISSUE THREAD

**Issue by lharv076** [opennorth/citizenbudgetapp.com#103]
@claudioccm @gmattar 

We deployed #100 yesterday and #102 today. If your changes aren't being displayed in production, there could be many reasons. 

@phildionne is going on vacation tomorrow until the 18th, so if there's still an issue he will give you leads to explore to try to fix the problem.

@jpmckinney Do you have any ideas as to what could be the issue?

**Comment by jpmckinney** [comment]
Can you describe the issue?

**Comment by phildionne** [comment]
I think @lharv076 is not seeing the changes in #100 and #102 in production. On my end, I deployed just as everytime with `git push ca1 master` and `git push ca3 master`.

**Comment by claudioccm** [comment]
@phildionne by any chance, is the deploy command returning any error?

Besides that, maybe if @gmattar can have access to the server, he could help. Let me know

**Comment by phildionne** [comment]
No, the command is not returning any error.

**Comment by lharv076** [comment]
Can we give @gmattar access to the server? Because @phildionne is on vacation as of tomorrow, we need to be able to move forward without him. 

Also note that @claudioccm and @gmattar can see the changes in their own version.

**Comment by gmattar** [comment]
@phildionne do you think [this](https://github.com/opennorth/citizenbudgetapp.com/wiki/Common-developer-tasks-%28Deprecated%29#expire-caches-in-production) could be the problem or is it really deprecated?

**Comment by jpmckinney** [comment]
I just need SSH keys to give access.

**Comment by claudioccm** [comment]
@jpmckinney, just sent you @gmattar's SSH key, via email

**Comment by jpmckinney** [comment]
I added @gmattar's SSH key and I fixed the git post-receive hook to just always recompile assets. (It previously only recompiled them if assets changed in the last commit.) Deploys will take a little longer, but at least they will be predictable now. I re-deployed ca1 and ca3. Let me know if changes are reflected!

**Comment by lharv076** [comment]
@claudioccm I made some changes to test.citizenbudget.com and measure.citizenbudget.com so technically the changes should be reflected in those consultations.

Let us know if they're not!

**Comment by gmattar** [comment]
@jpmckinney, it still doesn't show the new stuff. 

I logged into ca3 and checked the citizenbudget directory. The latest commit in the branch is a5e2045 from March 8, all other commits since then are not been shown.
After this, I cloned the `ca3.opennorth.ca:~/citizenbudget.git` into my local /tmp so I could check that it is up to date with https://github.com/opennorth/citizenbudgetapp.com. It is.
Therefore, I believe the `git pull origin master` command in the post-receive hook stopped going through at some point. A fast fix would be reset the HEAD to origin/master and run the commands inside the post-receive manually. This would fix the problem for now but doesn't explain it's origin.

Do you have any idea of what could have caused it and a better solution?

PS: I didn't check but the same problem must be happening in ca1.

**Comment by jpmckinney** [comment]
A `git` command in the hook was erroring, but I wasn't seeing the message because the push creates a lot of log lines. It should be fixed now and I re-pushed. ca1 is done. Waiting for ca3.

**Comment by jpmckinney** [comment]
@gmattar Some of your code for `range` assumed all values were integers. But values can be floats. Redeploying ca1 and ca3.

**Comment by jpmckinney** [comment]
@gmattar @claudioccm I don't see any sliders on e.g. http://measure.citizenbudget.com/?token=oUjCrC7uzRcbr9wkfZ9x Does this stuff work for you locally?

**Comment by gmattar** [comment]
Locally is fine. This seems to be happening due to URL issues, two JS files are not been find in production. I'm on it.

**Comment by jpmckinney** [comment]
I added all the shims to the list of assets that require compilation: https://github.com/opennorth/citizenbudgetapp.com/commit/8afd26367761832b571d01179c094e9a570da94a Redeploying.

**Comment by lharv076** [comment]
@jpmckinney All the consultations created by organisation "Open North" are returning the "Were sorry something went wrong" message.

Is this temporary? Or should I switch the demos to a different organisation while you look into it? (since are demos are live on citizenbudget.com)

**Comment by gmattar** [comment]
It's a bug that I already fixed in PR #104.

**Comment by lharv076** [comment]
wicked, thanks!

**Comment by gmattar** [comment]
I don't have permission to merge it. If you grant me write access while @phildionne is on vacation, I can merge and deploy it myself.

**Comment by lharv076** [comment]
@jpmckinney Can you merge and deploy #104?

**Comment by lharv076** [comment]
The consultations are fixed and I see your new sliders. Great job making this happen guys! Keep up the great work.

**Comment by lharv076** [comment]
@gmattar Are we able to fix the issues above today/tomorrow? I'm worried because we have live consultations.

Thanks!

**Comment by gmattar** [comment]
I'll check it right now.

**Comment by lharv076** [comment]
Let me know if I can help you in any way.

**Comment by gmattar** [comment]
Already got it. It was just an inline CSS setting the font color to white.

**Comment by lharv076** [comment]
What about the descriptions? (digbymuni.citizenbuget.com) They're very large and centered. As are the images.
